project:
  type: website
  output-dir: "_site"
  
bibliography: data/website.bib

website:
  title: "Matyas Levinsky"
  back-to-top-navigation: true
  reader-mode: true
  
  repo-url: https://github.com/matyasLevinsky/matyaslevinsky.github.io
  repo-actions: [edit, source]
  site-url: "https://matyaslevinsky.github.io/"
  
  favicon: data/favicon32.png
  open-graph: true
  google-analytics: "G-02CDV8B142"
  
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - text: "About Me"
        menu:
          - href: about.qmd
            text: "About Me"
          - href: cv.qmd
            text: "Curriculum Vitae"
      - text: "Data Projects"  
        menu: 
          - SlerkaProjekt.qmd
      - text: "Research Projects"
        menu:
          - href: AIHypeCycles.qmd
            text: "Analyzing AI Hype: Past and Present Booms"
      - text: "Guides"
        menu:
          - text: "Work in progress"
            
format:
  html:
    theme: 
      dark: [cosmo, theme-dark.scss]
      light: cosmo
    toc: true
    toc-expand: true
    toc-location: left
    df-print: paged
    reference-location: margin
    citation-location: margin
    fig-width: 9
    fig-height: 6

execute:
  freeze: auto

