project:
  type: website
  output-dir: "_site"
  
bibliography:
  - data/Website.bib
  - data/TheAIHypeCycle.bib
csl: data/apa.csl

website:
  title: "Matyas Levinsky"
  back-to-top-navigation: true
  reader-mode: true
  
  repo-url: https://github.com/matyasLevinsky/matyaslevinsky.github.io
  repo-actions: [edit, source]
  site-url: "https://matyaslevinsky.github.io/"
  
  favicon: data/favicon32.png
  open-graph: true
  google-analytics: "G-02CDV8B142"
  
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: cv.qmd
        text: "CV"
      - href: projects.qmd
        text: "Projects"
      - href: publications.qmd
        text: "Publications"
format:
  html:
    include-after-body: data/listing-categories.html
    theme:
      light: theme-brite.scss
      dark: [theme-brite.scss, theme-dark.scss]
    toc: true
    toc-expand: true
    toc-location: left
    df-print: paged
    reference-location: margin
    citation-location: margin
    fig-width: 9
    fig-height: 6

execute:
  freeze: true

