project:
  type: website

website:
  title: "Matyas Levinsky"
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"
      - href: cv.qmd
        text: "Curriculum Vitae"
      - text: "Projects"  
        menu: 
          - SlerkaProjekt.qmd
            
format:
  html:
    theme: 
      dark: [cosmo, theme-dark.scss]
      light: cosmo
    css: styles.css
    toc: true
    toc-expand: true
editor: visual

